### ISSUE TITLE
Support autoregistering any new modules via flexible wildcard directory configuration value.

### ISSUE THREAD

**Issue by litwol** [RexOps/Rex#1113]
Current approach requires explicitly declaring each module to be loaded in a Rexfile resulting in tens or hundreds of lines just to initialise Rexfile environment.

A possible improvement would be to support new configuration/command used inside Rexfile which will allow auto-discovering and auto-loading all found Rexfile(s) and modules from recursive directories as specified by this new configuration syntax.

For example:
```
set include_from => [  
  '/my-project/lib/**/Rexfile',  
  '/lib/**/Rexfile',  
  './**/Rexfile',  
  './**/*.rextask',  
]  
```

**Comment by ferki** [comment]
I've been thinking on this a lot.

I'd say that this is already possible via various Perl modules (see [How do I load all my custom modules easily?](https://www.rexify.org/docs/faq/index.html#howdoiloadallmycustommoduleseasily)), and since Rex code is just Perl code, any of those could be used for this purpose.

In other words, I'd prefer allowing the user to choose which module is the best for their use case, instead of either forcing one of those modules as a dependency of Rex, or implementing yet another custom module with similar functionality as part of Rex core.

Therefore, I'm closing this issue for now.
