### ISSUE TITLE
integration network vendors with Rex

### ISSUE THREAD

**Issue by ggmo** [RexOps/Rex#1257]
Will the Rex support Network vendor task deploy with follow features:
1、Integrate Rex with network DevOps tools chain;
2、Get open and full access to switch resources and data, like open switchport , design firewall policy;
3、support much vendor like CISCO-ACI F5 JUNIPER ARISTA CISCO-NX-OS and so on;
    just like ansible in python

**Comment by ferki** [comment]
Rex is developed by volunteers, so it supports whatever the community members are willing to implement and maintain. That being said, from the technological point of view, it is definitely possible to use Rex in those cases.

All the mentioned points probably would involve interacting with a device over SSH/SNMP/some other method, and/or with a service via some kind of API. Since Rex is just Perl, there's a good chance there's already some module that can be used, and perhaps it might just need some "glue" on top to call from Rex tasks. This means most of it is possible to implement as an extension module without modifying Rex itself (and we would be happy to bring in core-specific changes if needed).

Also, there are already some functionality in that direction, namely managing [OpenWrt remotes](https://www.rexify.org/docs/guides/manage_openwrt.html) and [interacting with iDRAC](https://metacpan.org/source/FERKI/Rex-1.7.1/lib/Rex/Interface/Shell/Idrac.pm) management consoles. There's also #783 open about working on Cisco support (sadly stalled though).

These features also mostly/largely depend on a developer having access to these kind of devices/services continuously, so these features are not just developed, but also maintained long-term. That means anyone having that access, and willing to implement and maintain this, is probably already in the best position to start working on this, with getting help from the Rex community.

For more details, including sponsored features and commercial support, please check out our [Help Rex](https://www.rexify.org/care/help__r__ex.html) and [Support](https://www.rexify.org/support/index.html) pages.

As this GitHub issue sounds more like a generic (support) question, I'm going to close this now. You seem to have interest in adding those features, and this is an interesting topic to further discuss, so please feel free to get in touch via IRC or mailing list.
