### ISSUE TITLE
Make rex bash completion script official

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#1289]
We have the `misc/rex-tab-completion.bash` script with us for a good while, and it has been proven useful and reliable. I'd say it's time to make it official and include it in the next release.

I'd expect things like this to do:
  - move the script into a more standard `share` directory
  - make sure Dist::Zilla/Manifest is configured correctly to include that directory in the releases
  - document usage (perhaps in `lib/Rex.pm`? see also RexOps/rexify-website#146)

**Comment by mestia** [comment]
I have a couple of suggestions regarding the bash tab-completion.

1. currently, bash tab completion doesn't support multiple Rexfiles in different dirs. After completing hosts or groups for one Refxile and navigating to a directory with a different Rexfile, completion will show wrong "old" hosts or groups. This can be fixed by calling `rex -Ty 2>/dev/null` in every completion call.

2. host completion. I'd like to complete not only hosts defined in a Rexfile, but also all hosts available via `_known_hosts_real` bash-completion function, which can extract hosts from my ~/.ssh/config for example. One can chain rex hosts and system hosts this way: `COMPREPLY=( $( compgen -W '${hosts[@]}' -- "$cur" ) ) ||  _known_hosts_real -a "$cur"` - by default complete rex hosts, if a different host is specified, complete it from `_known_hosts_real`

See: https://github.com/mestia/Rex/blob/master/misc/rex-tab-completion.bash
I'll open a PR if the stuff above makes sense.
