### ISSUE TITLE
Proposed new Description for https://metacpan.org/pod/Rex

### ISSUE THREAD

**Issue by sdondley** [RexOps/Rex#1308]
Here is a proposed new description for https://metacpan.org/pod/Rex. It's not finished but thought I'd get some input on this basic intro language. I'd like to get a good example that gives a good, concrete example of what paragraph 2 is talking about.

Rex is a framework for automating the execution of command line commands on multiple computers on the internet, on a local network, or even on a single local machine. Rex will do its best to abstract out the details out of the commands you provide so that the same command can run on any type of machine. For example, the `update_system` function that Rex provides will execute the appropriate commands for updating the operating systems of the target computer no matter which operating system it’s running.

While some automation frameworks prefer to force preferred solutions upon you, Rex does not. Instead, Rex focuses on designing tools to make it easy for you to create flexible task execution programs that work exactly how you’d like. Rex aims to get out of your way and let you be as creative as you wish and not impose any rigid structures on how you compose your scripts.

The Rex software distribution only needs to be installed on one machine, called the “control master.” All commands are issued from your Control Master out to the client machines, aka your “managed hosts.” None of the managed hosts need any special software to communicate except for an ssh daemon the Control Master will use to log into the remote machine and issue commands. The only other requirement is that the managed hosts have a perl interpreter installed.

Rex scripts are written in Perl. While knowing Perl may help you pick up Rex faster, you don’t need to know a lot of Perl, or any at all, really, to be productive with Rex. Rex is designed to make automation scripts easily readable and can be created by Perl novices without an extraordinary amount of effort.

**Comment by ferki** [comment]
Overall I like the effort and idea, while placement- and content-wise there's probably quite a few refinements possible. This approach feels more like an intro to a beginner's guide (which I believe is _the_ intent :+1: ), that mixes some bits of the getting started guide with elements of the "Rex philosophy"/"Rex values" described in the README and on the website.

Personally, I'd probably go for consistency and put the main ideas into the main POD, then improve the getting started guide separately (either directly in the website repo, or discussing and deciding that the content should be moved into the codebase as something like Rex::Manual::Intro, to be rendered both on MetaCPAN and the website).

Since the main purpose of this issue seems to be sharing a proposed text, I'll close it for now, and we can go ahead and create actionable issues or proper user stories once we have a better grip on what exactly needs to be done or changed.
