### ISSUE TITLE
Enable usage of `Net::OpenSSH` instead of `Net::SSH2` on Windows for SSH agent support

### ISSUE THREAD

**Issue by zhiyuan-lin** [RexOps/Rex#1316]
I am a Rex beginner and I was trying to use Windows 10's native ssh-agent to login to a Linux server.
My environment is:

Windows 10 Pro 1909 Build 18363.815 x86-64
Strawberry Perl v5.30.2

My Rexfile is as following, based on the guide https://www.rexify.org/docs/rex_book/the_rex_dsl/authentication.html

```perl
use v5.30;
use strict;
use warnings;
use Rex -feature => ['1.10'];

user 'ubuntu';
public_key 'C:\Users\User\.ssh\id_ecdsa.pub';
private_key 'C:\Users\User\.ssh\id_ecdsa';

group myservers => 'serverhostname';

desc 'Get the uptime of all servers';
task 'uptime',
  group => 'myservers',
  sub {
    my $output = run 'uptime';
    say $output;
  };
```

On a Linux machine, this would work properly since it uses `Net::OpenSSH`, however on Windows 10 even if I have the SSH Agent properly set up it cannot connect to the server due to some quirks between the system SSH agent and `Net::SSH2`.

The error messages is as following:
```
1 out of 1 task(s) failed:
uptime failed on serverhostname
       Couldn't authenticate against serverhostname. It may be caused by one or more of:
        - wrong username, password, key or passphrase
        - changed remote host key
        at C:/Strawberry/perl/site/lib/Rex/TaskList/Base.pm line 342.
```

I solved this issue by changing the line:
https://github.com/RexOps/Rex/blob/master/lib/Rex/Config.pm#L1333

From
```perl
if ( $^O !~ m/^MSWin/ && !$connection_type && $use_net_openssh_if_present ) {
```
To
```perl
if ( !$connection_type && $use_net_openssh_if_present ) {
```
So the Rex will attempt to use `Net::OpenSSH` if available, which works better for SSH Agent on Windows 10.
Maybe this work around to default to `Net::SSH2` for Windows users should be removed, since `Net::OpenSSH` is now less buggy than the former.
User can still choose to use `Net::SSH2` by configuring:
```perl
Rex::Config->set_use_net_openssh_if_present(0);
```
Maybe there should be a config option for choosing specific SSH library as well.

Should I make a pull request to fix the issue?

**Comment by ferki** [comment]
@zhiyuan-lin: thanks for the detailed report, and welcome to Rex!

> Maybe there should be a config option for choosing specific SSH library as well.

In the same file, just a bit below, there's a set handler registered for `connection_type` under the name of `connection`:
https://github.com/RexOps/Rex/blob/master/lib/Rex/Config.pm#L1851

This means it's possible to set a specific connection type like this in the Rexfile:

```perl
 set connection => 'OpenSSH';
```

If that solves your immediate issue, I don't think a PR is needed/warranted. Thanks for discussing it first, though!

I'd like to invite you to join the discussion on our IRC channel as well, especially if you are looking for the community support to answer questions like this, or interested in contributing.

ps.: the current defaults around this, and frankly, `Net::SSH2` support is mainly there for backwards compatibility reasons from times where the only real option on Windows was using `Net::SSH2`. Times has changed since then, so Rex should change too in this regard. Most probably we will start doing some managed deprecations sooner or later.

**Comment by zhiyuan-lin** [comment]
Thank you for reply, I closed the issue because I discovered `Net::OpenSSH` does not work reliably on Windows, I have only successful running the `uptime` task once and after I made some changes the script just fail silently without error message, still don't know why. Meanwhile `Net::SSH2` just works if I use username/password authentication.

It seems currently the most pain-free way to use ssh-agent on Windows is using a WSL Terminal.

**Comment by ferki** [comment]
> Thank you for reply, I closed the issue because I discovered `Net::OpenSSH` does not work reliably on Windows

I'm a bit sad to hear that, since I was looking forward to be able to unify SSH handling in Rex. Nevertheless, thank you very much for the update about your experience on Windows!

> Meanwhile `Net::SSH2` just works if I use username/password authentication.

Good to know that the alternative backend is still useful :+1:

> It seems currently the most pain-free way to use ssh-agent on Windows is using a WSL Terminal.

Now that you mention WSL, I think people had success with cygwin environments as well. Personally I don't have much experience though, as I don't have access to a Windows setup beyond what is offered for testing by Travis CI.
