### ISSUE TITLE
Rex::Commands::Sysctl sysctl key => 0 works as getter

### ISSUE THREAD

**Issue by uralm1** [RexOps/Rex#1320]
task "noforwarding", "server01", sub {
   sysctl "net.ipv4.ip_forward" => 0, ensure => "present";
 }

when value is 0, sysctl function always operates as getter.
line 90 of Rex::Commands::Sysctl should be: if (**defined** $val) {...

and please add sysctl_save, sysctl_remove functions to @EXPORT

**Comment by ferki** [comment]
Thanks for the report! It even seems to be a real all-in-one: a bug report, a "kind of" pull request, and a feature request :upside_down_face:

It might need more than one steps to address all those, and/or going to be harder to close due to multiple things to be addressed in relation to this.

> when value is 0, sysctl function always operates as getter.

Nice catch, sounds like a bug indeed.

> line 90 of Rex::Commands::Sysctl should be: if (defined $val) {...

Thanks for the pointer! Without taking a look at the code context, the does look like a fix for this kind of issues :+1: 

> and please add sysctl_save, sysctl_remove functions to `@export`

Thanks for suggesting the idea. Could you elaborate more on your use case or context for this, please? Judging by git history, their purpose seem to be purely helpers for the `ensure` option of `sysctl`, and were not intended to be called directly. Is there something you can't do with `sysctl [...], ensure => [...]` (apart from the above bug)?

**Comment by uralm1** [comment]
Well, I dont insist :)
I had to modify /etc/sysctl.conf on a bunch of routers. There was no requirement to apply setting immediately, there were other changes like modifing ip, etc... For me, I checked 3 methods to do the task:
- modify sysctl.conf directly with append_or_amend_line() for example,
- keep template of sysctl.conf and replace it entirely,
- use sysctl function.

I choosed the second variant with template.
Looked for the first, it takes to much code to do (there were ~15 sysctl lines to change). And found that sysctl_save() function does mostly the same in one call. <- THE CASE
Could call it via full path Rex::Commands::Sysctl::sysctl_save() or functional pointer to keep typing, but import approach looks better.
sysctl() operator takes too much overhead (of running sysctl utility over the link) and didn't work good - because of bug I reported.

**Comment by ferki** [comment]
Thanks for explaining the additional context, I've fixed the bug for the next release.

In general, I would also recommend the file template approach if there are more than just a few parameters to set.

Since there are a few alternatives already available depending on the situation, I decided to not extend the public API in the context of this issue.
