### ISSUE TITLE
Feature request:  Diff flag for Rex::Commands::File and Rex.

### ISSUE THREAD

**Issue by einhverfr** [RexOps/Rex#1412]
## User story

**As** an engineer
**I would like to** see how a file I am about to deploy differs from production
**so I can** make sure my changes are safe on critical systems before I deploy.

## Describe the solution you'd like

A general option for a file-by-file diff of the file on the running system vs the file that would be deployed.  In this case we would not deploy the file at all but just upload it to /tmp and diff instead of copying over.

## Describe alternatives you've considered

Adding file-by-file diffs to all existing jobs....

## Additional context

there are a lot of cases where we deploy single config files to servers.  It would be nice to be able to run some spot-checks against some production servers ahead of time, for example saying "I want to know how my nginx config is going to change in this deployment" before I do.  In a fleet of servers this could be run on a couple of servers in order to ensure sanity before eing rolled out.

there are cases not covered in this such as whole directories.  In this case, you would not be able to diff against a file currently in /etc/nginx/sites-enabled that had been removed and would no longer be deployed (though ensure => absent might allow that sort of diff optionally).

**Comment by ferki** [comment]
Thanks for the interesting idea, @einhverfr! At first it sounds like a job for a custom file hook to me, but I'll keep this issue open for a while in case we end up having to modify Rex core for supporting this (e.g. with some sorts of generic `inhibit` flag in the API).

> A general option for a file-by-file diff of the file on the running system vs the file that would be deployed.

For the diffing itself, I maintain a separate [Rex::Hook::File::Diff](https://metacpan.org/pod/Rex::Hook::File::Diff) module, you might be interested to take a look at that.

Perhaps we can somehow enable that hook to inhibit the actual copy of the new file (or just replace the file with itself to end in an effective no-op without having to modify Rex core).

> In this case we would not deploy the file at all but just upload it to /tmp and diff instead of copying over.

In general, I believe it's best to keep the current behavior and write the new file to the same directory where the target is located.

I'm often tempted to play with uploading files to a different directory than where the managed file is located (e.g. to `/tmp`), but that is always quickly followed by permissioning problems. Like the simulation shows it will succeed, but then the user running rex doesn't actually have permissions to write to the target directory (has only read permissions there, and write permissions to the alternative (`/tmp`) location).

**Comment by ferki** [comment]
Hmm, the more I think about it, the more certain I am that this should be implemented as a custom file hook, instead of adding yet another flag to the built-in file command(s) and making it even more complicated. There are even more than one way to do it. Depending on the exact needs there are probable other approaches available, but two ideas to get started:

- The bit hacky way is to use a `before_change` hook to replace the already written intermediate rex temp file with the original file. This essentially would copy the target file over itself instead replacing it with the new content.

- Perhaps a bit more appropriately it could be a `before` hook that copies the original file to another location that is used for this diffing (e.g. `/tmp/rex_preview`), which then overwrites the parameters of the original call. So the rest of the process would work with the copy in the preview location instead of the real target file.

This hook could be also dynamically applied depending on some condition, e.g. the presence of a specific task option on the CLI (like `--preview`).

There could also be more than one hook defined even for the same type of hooks. So any of the above could be either combined with Rex::Hook::File::Diff, or with another custom hook that is written for the exact use case at hand (like using the `diff` command, or `Text::Diff` module, etc.).

**Comment by ferki** [comment]
As slightly related news, file hook functionality was improved on #1423 to make these use cases (combining multiple hooks, and `before` hook modifying original options) easier to write with less code than before.

For the overall goal to "make sure my changes are safe on critical systems before I deploy", I'd advise using some kind of tests on top of (or instead of) diffing. For example the same or another hook could check the new content against a set of expectations (or call a linter, or run custom `$software --check $file`, etc.) to further assist the operator checking for correctness.

In summary, the diffing half of the story is already available via the [Rex::Hook::File::Diff](https://metacpan.org/pod/Rex::Hook::File::Diff) module, and the "don't overwrite the original file" half can be implemented with `before` or `before_change` hooks, depending on the exact requirements.

Doing similarly for directories: a task may check for the presence of a given CLI option (`--preview`) to prepare/upload the directory at a "staging area" (e.g. under `/tmp`), then show the diff compared to the target before cleaning up and exiting. If the CLI option is not present, it can decide to write directly to the target location without diffing.

All these cases seem highly depending on the exact use case requirements, and I don't see any obvious need to modify the core, so I'm going to close this one for now. Hopefully all the examples above are giving enough inspiration to anyone reading this to be able to implement the required logic for their own use case (or to even wrap that up as a module on its own and share it via GitHub/CPAN/etc.).

**Comment by ferki** [comment]
To anyone looking at this later: thanks to my [GitHub Sponsors](https://github.com/sponsors/ferki), a new module called [Rex::Hook::File::Impostor](https://github.com/ferki/Rex-Hook-File-Impostor) is now available to implement such functionality when used together with [Rex::Hook::File::Diff](https://metacpan.org/pod/Rex::Hook::File::Diff).
