### ISSUE TITLE
Rex::Commands::Gather network interface naming

### ISSUE THREAD

**Issue by LeMerP** [RexOps/Rex#1461]
Hi guys,

is there a reason why the function get_operating_system() converts network interface names containing "-" to "_"?
Let's say, if the interface on the target device is "bond-intranet" then the function returns "bond_intranet".

Kind regards,
Patrick

**Comment by ferki** [comment]
Hmm, this doesn't look like a bug report or feature request, so perhaps it would have been a better fit for one of our [support](https://github.com/RexOps/Rex/discussions) channels.

I'm also a bit confused because `get_operating_system()` should not return the interface names, but the name of the operating system rex detects on its target.

But otherwise, the general reason to do such conversion is to make sure that the name can be used as a perl variable (for example in templates). If it's causing a bad interaction with interface names, we might need to take a closer look at both the use case and the code.

Should you need further help for investigation, please follow up on one of our support channels!
