### ISSUE TITLE
Run.pm documentation A little improvement

### ISSUE THREAD

**Issue by zhumengu** [RexOps/Rex#1486]
https://github.com/RexOps/Rex/blob/df033cee5be8011207df9f5269bb25d74b94550f/lib/Rex/Commands/Run.pm#L134

`ps -ef | grep -v grep  | grep -q httpd`

**Comment by ferki** [comment]
Thanks for your report, @zhumengu, and for your patience!

This issue does not fully follow the project's expectations, so I'd like to take this chance to kindly link our [Contributing guide](https://github.com/RexOps/Rex/blob/master/CONTRIBUTING.md), specifically the section about [GitHub issues and pull requests](https://github.com/RexOps/Rex/blob/master/CONTRIBUTING.md#github-issues-and-pull-requests).

---

If I guess correctly, the real message here is that the provided code example may contain a bug, because the `grep` command would find itself in the process list from `ps` while running. That is a good catch, thanks! :+1: 

I think I'll go and simplify this example to use `pgrep` instead, and/or generally reformat that section a bit.
