### ISSUE TITLE
[doc] desc command doesn't mention documenting batch as well as task

### ISSUE THREAD

**Issue by rwp0** [RexOps/Rex#1534]
### Describe the bug

[desc](https://metacpan.org/pod/Rex::Commands#desc($description)) says:

Set the description of a **task**.

```perl
desc "This is a task description of the following task";
task "mytask", sub {
  say "Do something";
}
```

but it also describes `batch`es as well as seen in `rex -T` output.

I don't know if the `desc` is used anywhere else (apart from the `-T` output).

### Expected behavior

Mention describing batches and give a code example in addition to task.

### How to reproduce it

- `perldoc Rex::Commands`
- read [Rex::Commands::desc](https://metacpan.org/pod/Rex::Commands#desc($description))
- run `rex -T` with a Rexfile contaning a task and a batch with their description set (to witness both are being documented)

### Additional context

I initially thought `desc` is part of `task`, and hence was wondering for a while why it was not including as a docstring implemented as another option argument of the task command instead of preceding it as a separate independent command.

Rex::Commands synopsis section also implies documenting task only:

```perl
desc "Task description";
task "taskname", sub { ... };
task "taskname", "server1", ..., "server20", sub { ... };
```

I'm not aware if [`desc`](https://github.com/RexOps/Rex/blob/master/lib/Rex/Commands.pm#L364) will document anything else as well such as hosts, groups, and so on.

Looking at the source seem like [`environment`](https://github.com/RexOps/Rex/blob/master/lib/Rex/Commands.pm#L1167) command uses `desc` as well, but I haven't been using that so far, hence not sure what it really is.

### Rex version

1.13.4

### Perl version

5.36.0

### Operating system running rex

Debian 11

### Operating system managed by rex

FreeBSD

### How rex was installed?

cpan client

**Comment by ferki** [comment]
Thank you for the detailed bug report, @rwp0! :heart:

Your analysis is correct: `desc` can also provide a description for batches and environments, not just tasks. These cases are indeed not mentioned in the docs, neither in the code example there.

Since the code example would be touched as well, it would be also a good opportunity to clean up the style of the related code example as a secondary optional goal (e.g. use single quotes instead of double quotes when nothing is interpolated, use 4 spaces indent instead of 2, etc.).
