### ISSUE TITLE
Rex::SCM::Git can't clone into existing empty directory

### ISSUE THREAD

**Issue by qbit** [RexOps/Rex#1537]
### Describe the bug

Git has been capable of cloning into an existing, empty directory since commit https://github.com/git/git/commit/55892d23981917aefdb387ad7d0429f90cbd446a.

Currently Rex will attempt to clone, see that the directory exists and fall through to this statement: https://github.com/RexOps/Rex/blob/master/lib/Rex/SCM/Git.pm#L146

### Expected behavior

Rex should be able to clone a git repository into an existing directory.

### How to reproduce it

Clone a repo into an existing directory

### Rex version

1.13.4

### Perl version

v5.34.1

### Operating system running rex

NixOS, OpenBSD

### Operating system managed by rex

OpenBSD

### How rex was installed?

package manager

**Comment by ferki** [comment]
Thanks for the report, @qbit! It is indeed failing with Rex, but succeeds when attempting an equivalent operation manually.

For reference, I've used the following command to reproduce with non-existing target, as well as in cases when the target already exists as a file, empty directory, or non-empty-but-not-git directory:

```bash
rex -e 'use Rex::Commands::SCM; set repository => q(rex), url => q(https://github.com/RexOps/Rex.git); checkout q(rex), path => q(/tmp/rex)'
```

I took a closer look and summarized my thoughts below.

## First impression

It looks like the current approach is something like (meta code):

```
if ( target_is_not_a_directory ) {
    try_to_clone
}
elsif ( target_looks_like_a_git_repo ) {
    try_to_pull
}
else {
    abort_due_to_unknown_situation
}
```

Since both the cloning and pulling logic has its own error checking, I believe it would be safe to reorder/simplify the overall structure into:

```
if ( target_looks_like_a_git_repo ) {
    try_to_pull
}
else {
    try_to_clone
}
```

## Alternative approach

One alternative is to detect and classify the target environment into something like `$is_safe_to_clone` exactly how `git` thinks about it, and use that as a condition to decide between cloning or pulling actions. Which feels like an unnecessary overhead, and also harder to maintain to always keep in sync with potential (though unlikely) changes in `git` behavior. So I'd probably avoid this approach.

## Testing

Looks like the related code is still without tests, so it would be nice to add some before changing the code.

I would avoid using the network from tests, so I wonder how it would be best to approach this. Perhaps a test may look something like this:

- detect if `git` is present, and skip if not available
- setup an empty/simple local git repo, and use that as source to clone/pull/etc.
- test git clone in various scenarios (using a preexisting target directory would fail now, but would pass after a fix)
- ideally test pulling and/or checking out branches, tags, etc.
- tear down any test repos/files/dirs when exiting

**Comment by ferki** [comment]
[Test::Git](https://metacpan.org/pod/Test::Git) is probably useful for the testing part.

**Comment by ferki** [comment]
I've pushed a draft of the proposed fix to the [git_clone_into_existing_dir](https://github.com/RexOps/Rex/tree/git_clone_into_existing_dir) branch.

No tests for it yet, but works as expected in manual cases, and it might come in handy until a full PR comes.
