### ISSUE TITLE
Rexfile load tests fail with blead perl

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#1585]
### Describe the bug

Perl 5.37.4 adds a [new error](https://metacpan.org/release/ETHER/perl-5.37.4/view/pod/perldelta.pod#New-Errors) about

> Execution of %s aborted due to compilation errors.

as a

> final summary message when a Perl compilation fails.

Related follow-up changes cause `t/load_rexfile.t` tests fail checking expected output upon loading failure when using perl versions 5.37.9 or later.

### Expected behavior

Rexfile loading tests should pass with recent Perl versions.

### How to reproduce it

1. install Perl 5.37.9 or newer
2. check out the default branch of the Rex repo
3. run Rexfile loading tests with `prove -l t/load_rexfile.t`

### Code example

Code example omitted intentionally.

### Additional context

Related CPAN Testers reports:

- [247d3746-e28c-11ed-8f91-53a5c300e77a](http://www.cpantesters.org/cpan/report/247d3746-e28c-11ed-8f91-53a5c300e77a)
- [ce4c7ab4-e301-11ed-a3c6-d4efc900e77a](http://www.cpantesters.org/cpan/report/ce4c7ab4-e301-11ed-a3c6-d4efc900e77a)

### Rex version

1.14.1

### Perl version

5.37.11

### Operating system running rex

Ubuntu Jammy/Focal

### Operating system managed by rex

local

### How rex was installed?

cpan client

**Comment by uralm1** [comment]
Hello, @ferki ! 
:irony: This is the most change in perl in last 22 years.:irony:
I see two solutions:
1. Create somewhat like regexp matching for test templates files (so we can insert optional blocks of text into it). Cons: this involves multiline regex matching (don't like it). I'm going to rename sample files like: Rexfile_noerror_print.stderr.regex and add regexp codes to its content. Use Test::Output::output_like instead of output_is.
2. Rewrite test logic back from loops to linear, and check results by regexps individually. Pros: test logic become linear and cleaner.

I prefer first, probably it is the easiest. Going to test it somehow.

**Comment by ferki** [comment]
Hi @uralm1! :wave: 

On first look, it seems this only affects two files (the "fatal" ones), and there's already an if condition for those (to set the expected exit code).

So my idea was to `use English` to check `if ($PERL_VERSION ge v5.37.4)`, and if yes, add an extra line to the expected content read from the reference output files.

Or perhaps do the reverse: add the missing new lines to the reference output files, so they reflect the current reality on the most recent perl version (as in "most recent Perl is the baseline"), and remove this extra line from comparison `if ($PERL_VERSION lt 5.37.4)`.

Since this new error message is only present a development Perl version so far, I also wondered whether we should wait until an actual stable Perl release has it or not. I probably would prefer having something ready to merge and release, just in case.

**Comment by ferki** [comment]
Apparently the first perl version to cause troubles for the Rex test suite is 5.37.9. I'll update the description accoringly.
