### ISSUE TITLE
Possible precedence problem between ! and string eq

### ISSUE THREAD

**Issue by eserte** [RexOps/Rex#1624]
### Describe the bug

Test suite fails with bleadperl (e.g. 5.41.5):
```
Possible precedence problem between ! and string eq at /home/cpansand/.cpan/build/2024103100/Rex-1.14.3.1-1/lib/Rex/Shared/Var/Array.pm line 83.
Possible precedence problem between ! and string eq at /home/cpansand/.cpan/build/2024103100/Rex-1.14.3.1-1/lib/Rex/Shared/Var/Array.pm line 100.

#   Failed test 'no (unexpected) warnings (via END block)'
#   at /opt/perl-5.41.5D/lib/5.41.5/Test/Builder.pm line 193.
# Looks like you failed 1 test of 140.
t/0.31.t ........................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/140 subtests 
... etc ...
```

### Expected behavior

Test passes

### How to reproduce it

See above.

### Rex version

Rex-1.14.3.1-TRIAL

### Perl version

5.41.5

### Operating system running rex

any

### Operating system managed by rex

any

### How rex was installed?

cpan client

**Comment by ferki** [comment]
Thanks for explicitly reporting this, @eserte! FYI, I also actively monitor CPAN Testers results, thank you for your results over there.

For more context, what happens here is the following:

- perl-5.41.4 introduced a [new warning](https://perldoc.perl.org/5.41.4/perldelta#New-Warnings) about [Possible precedence problem between ! and %s](https://perldoc.perl.org/5.41.4/perldiag#Possible-precedence-problem-between-!-and-%25s)
- this is an [example CPAN Testers report](http://www.cpantesters.org/cpan/report/0bd6bb04-7a3e-11ef-87d9-137576847d3d)
- #1619 now fails the test suite on any warnings (since 67390337f4eff6c14ea68851c3460fbed43c7aae), including this one (and it's so nice to see it in action now with the latest Rex trial release, as this warning was silently passing before)
- we unfortunately don't test with blead Perl here in GitHub Actions, due to actions-setup-perl not supporting that (yet? see also shogo82148/actions-setup-perl#1444)
- we also have a `ValuesAndExpressions::NotWithCompare` perlcritic policy violation about the same issue

I expect it would be trivial to fix by replacing the `!... eq ...` with `... ne ...` – in fact, locally that passes tests, so I'm going to open a PR soon.
