### ISSUE TITLE
exit_status is not very transparent

### ISSUE THREAD

**Issue by aowi** [RexOps/Rex#400]
With exit_status enabled by default since 0.50, Rex has started to return 255 for us every now and then, with no sign of the actual error in the output from Rex.

Internally, there is one or two -1's in @exit_codes. lib/Rex/CLI.pm:549:

``` perl
@exit_codes = Rex::TaskList->create()->get_exit_codes();
```

The feature itself is both good and something we want to use, but just using the first non-zero exit code returned from any of the tasks tells us nothing about what went wrong or where it went wrong. This makes it very hard to figure out why something failed. 

The fact that Rex got an exit code of -1 is also somewhat baffling.

There's also no nice way (as far as I can tell) to disable this feature. For now, we've just set `$Rex::WITH_EXIT_STATUS = 0` in the Rexfile as a workaround.

Things that would be nice to have:
- [x] Configurable exit_status
- [x] Per-task output of exit status, to make post-mortem possible
- [x] No -1's without a good explanation in the output. Whatever caused these should probably also have made Rex yell at me.

Since I don't know the exact source for the last issue, it might not actually be a problem.

I'm more than happy to fix this myself, I'd just like to touch base before I do it.

**Comment by krimdomu** [comment]
For 1.1 we are not at the point to get this better. So i added it to the backlog. I have to take a deeper look at the code how to solve this.

**Comment by eskaaren** [comment]
+1

Also when Rex exits from no Rexfile or no task found the exit code is 0 when it should be 1 or 255 or whatever so that external programs like Jenkins can fail.

**Comment by kablamo** [comment]
I think this pr will go a long way to resolving all the issues mentioned here:
https://github.com/RexOps/Rex/pull/697

**Comment by kablamo** [comment]
Status update on the things people want solved in this issue:

 - [ ] **Configurable exit_status** - If you don't want rex to exit with exit codes, then don't use the 'exit_status' feature?  I guess I don't understand this one.  

 - [x] **Per-task output of exit status, to make post-mortem possible** - This is merged into master in #697 .  See the pr description for details.

 - [x] **No -1's without a good explanation in the output.** - This was also fixed in #697 .  I can't remember the details now, but I believe the exit code 255 and -1 issues are the same or very related..  Here is an explanation: https://github.com/RexOps/Rex/issues/761 and here is the commit that fixed the problem: https://github.com/kablamo/Rex/commit/d0b67aed2480311b51fe9b1a505050cd437cbc22

 - [ ] **When Rex exits from no Rexfile the exit code is 0 (from @eskaaren )**  - No Rexfile is not always an error.  For example, you can do `rex -e 'say run "hostname"'`.  Rex::CLI should `exit(1)` when appropriate.

 - [ ] **When Rex exits from no task found the exit code is 0 (from @eskaaren )**

**Comment by ferki** [comment]
Note on `exit_status`: exiting with proper exit code was not a feature in the beginning. Then `exit_status` feature flag appeared in 0.39.0 to be an opt-in for users who needed this feature. Then it was enabled by default in 0.50.0.

I guess if we can make sure it really works realiably (~ we have tests for it), we can just drop the feature flag, or just leave it as is (so we don't break those people's user cases who  have this in their Rexfiles; or, doing a planned deprecation would be even better). I think we're close to this point ;)

**Comment by kablamo** [comment]
Thanks @ferki .  Are you just reminding me?  Or is this in response to a mistake I made somewhere?  Or is this a wishlist item?

A planned deprecation is a good idea.  I would love to go through and try to deprecate a bunch of stuff one of these days, but I don't want to get distracted from my current goal atm.

**Comment by ferki** [comment]
@kablamo: I just reflected on your
>If you don't want rex to exit with exit codes, then don't use the 'exit_status' feature? I guess I don't understand this one.

point from above - no mistakes were made :)

As far as I understand the situation, returning proper exit codes were already done and working at some point in time (since the feature flag for this behaviour has been enabled by default), but unfortunately it seem like since then it got broken (maybe only in some cases?).

My wishlist item is to let's prevent that by adding tests for exit codes.

**Comment by kablamo** [comment]
I would like to do that too.  Its a hard problem though because there isn't an easy way to trap the `CORE::exit()` calls in `Rex::CLI`.  I would normally use `Test::Exit` for that -- it can trap calls to `exit()` but it doesn't work with `CORE::exit()`.  

My personal preference is to someday deprecate and remove `Rex::Commands::exit()`.  People shouldn't be calling `exit()` inside the Rexfile anyway.  

I'll see if I can come up with a work around.

**Comment by ferki** [comment]
@kablamo: I propose opening a new issue for tracking the "tests for exit code", so here we can focus on resolving the last remaining elements from your list above.

- I think `Configurable exit_status` can be crossed off for now (and maybe we can create another tracking issue about things that should be deprecated, and add it there)
- `When Rex exits from no Rexfile the exit code is 0` can now be worked on since #778 has been merged
- `When Rex exits from no task found the exit code is 0` is reported on #841 too, and #729 is at least partially related

@aowi: would you still feel the need to add a feature flag to disable returning exit codes once we fixed the behaviour? I couldn't come up with a use case for that on my own, but you might have one :)

**Comment by ferki** [comment]
@eskareen: I believe the `When Rex exits from no Rexfile the exit code is 0` problem is alrady solved:
```bash
$ ls -l Rexfile
ls: cannot access Rexfile: No such file or directory
$ rex -q -e "run 'hostname'"; echo $? # no Rexfile, eval
0
$ rex -q no_task; echo $? # no Rexfile, task
1
$ touch Rexfile
$ rex -q -e "run 'hostname'"; echo $? # Rexfile, eval
0
$ rex -q no_task; echo $? # Rexfile, non-existing task
1
$ rex -q -f ~/Rexfile existing_task; echo $? # Rexfile, existing task
0
$ rex -q -f ~/Rexfile -e 'run "hostname"'; echo $? # other Rexfile, eval
0
$ rex -q -f ~/Rexfile no_task; echo $? # other Rexfile, non-existing task
1
$ rex -q -f ~/Rexfile existing_task; echo $? # other Rexfile, existing task
0
```

Do you have any other cases related to the combination of Rexfile's existence and the exit code?

**Comment by ferki** [comment]
@eskaaren

**Comment by ferki** [comment]
@aowi: I believe all your original items here has already been addressed.
- Configurable exit_status: exit codes are believed to be working correctly by now, the `exit_status` feature flag can be disabled with `$Rex::WITH_EXIT_STATUS = 0`, and we don't see a reason/use case to endorse doing that with a `no_exit_status` feature flag (though it might come later anyway as we would like to add feature flags in pairs of enablers/disablers)
- Per-task output of exit status, to make post-mortem possible: if not all tasks are considered successful, failing tasks are now showed in the summary
- No -1's without a good explanation in the output. Whatever caused these should probably also have made Rex yell at me: Rex's exit code is 0 on success, 1 on abort (when `SIGINT` receieved via e.g. `CTRL-C`), and the exit code of the first failing task's exit code otherwise (task exit codes are the exit codes of the remote commands' as returned by the execution layer)

I'll keep this issue open for a bit more and mark it as `info needed`.

**Comment by eskaaren** [comment]
@ferki Ok, thanks. No I don't have another example.
