### ISSUE TITLE
multiple groups execution on cli

### ISSUE THREAD

**Issue by Azryel** [RexOps/Rex#516]
Hi,

I needed to execute a task on multiple groups without creating a group with them into.
rex -h says :   -G|-g           Execute task on these group
Sooo.. these but no s.
Anyway it did not seem to work in any way, so i added that to Rex::TaskList::Base :

```diff
--- /usr/share/perl5/vendor_perl/Rex/TaskList/Base.pm.old       2014-12-31 10:41:16.000000000 +0100
+++ /usr/share/perl5/vendor_perl/Rex/TaskList/Base.pm   2014-12-31 10:40:11.000000000 +0100
@@ -69,6 +69,18 @@
 
         push @server, sub {
           if ( !Rex::Group->is_group($group_name) ) {
+            if ($group_name =~ /,/) {
+              my @groups = ();
+              for (split /,/, $group_name) {
+                if (Rex::Group->is_group($_)) {
+                  push @groups,Rex::Group->get_group($_);
+                } else {
+                  Rex::Logger::info( "No group $_ defined.", "error" );
+                  exit 1;
+                }
+              }
+              return @groups if @groups;
+            }
             Rex::Logger::info( "No group $group_name defined.", "error" );
             exit 1;
           }
```
It seems to work for me now just with a ",".
i've never posted any patch on github before, i don't know if this is any good, but i needed this feature :P

**Comment by krimdomu** [comment]
Hi Azryel,

thank you for this patch and sorry for the late response.

I can manually merge this, if you want. This is no problem. 

The normal way is to do a fork of the rex repository into your private namespace. Then you can do your changes and send a pull request. With this it is easier to merge and the history in the commit logs shows you as the author of this snippet.

So if you want to do a merge request, just let me know, then i'll wait for it.

Cheers,
Jan

**Comment by ferki** [comment]
Although it can be merged manually, I would prefer using a pull request as they can be tested before merging to master :)

Also this patch seems to duplicate code for checking if a group exists or not - there might be a cleaner solution for this problem.

**Comment by reneeb** [comment]
I would prefer if one could specify multiple "-g"'s

rexify -g group1 -g group2

Currently the argument parser cannot handle "array" options and the use of $::FORCE_SERVER variable is a bit obscure (if it begins with \0 then it is groups, otherwise it can be a comma separated list of servers...) ;-)

If you agree, I would rewrite that handling:

Allow some options to be arrays, remove $::FORCE_SERVER and use a better variable where groups and servers can be stored (most probably a hash). That would have an other benefit, too: groups and servers can be mixed....

rexify -g group1 -s server101

so that the task is done on each server in group1 and on server 101

But this rewrite would have to wait until end of January as I'm busy at the moment.

**Comment by krimdomu** [comment]
Hi renneb,

yes, this code is indeed obscure and need to be refactored :)

I would be glad to see a patch from you. And take your time, we are not in a race :)

**Comment by chenryn** [comment]
@reneeb ++

I had thought to rewrite rex-cli by MooX::Options or App::Cmd for a long long while, but didn't have a really start...

**Comment by krimdomu** [comment]
#516 is now merged into master branch.
So with the next release it is possible to define multiple group parameters with:

```
rex -g group1 -g group2 taskname
```
