### ISSUE TITLE
failed authentication when used ~ symbol

### ISSUE THREAD

**Issue by ki0** [RexOps/Rex#517]
Hi there,

When i try to used that simbol on Rexfile, the authentication method fails if i use full path to the rsa, everything works perfect. This issue is happening to me from a long time ago, version 0.40. I use Macox and perl 5.16.3, 5.18.4 and 5.20.1. 

Cheers

**Comment by petersonchen** [comment]
below is the workaround I currently used :

private_key  glob(~/.ssh/id_rsa);

http://stackoverflow.com/questions/1475357/how-do-i-find-a-users-home-directory-in-perl/1475447#1475447

**Comment by krimdomu** [comment]
Hi @ki0,

thank you for the report. We will look into that.

@petersonchen
Thanks for the workaround.

**Comment by krimdomu** [comment]
Hi,

this bug should now be fixed in the master branch. If you want, you can download the Task.pm file and replace the one from your installation. This fix will be included in the next release.

The file:
https://raw.githubusercontent.com/RexOps/Rex/6d3748a8333bf74f2984c3d8e57747043db42850/lib/Rex/Task.pm

HTH,
Jan
