### ISSUE TITLE
Parsing of primary network ip address

### ISSUE THREAD

**Issue by samuelet** [RexOps/Rex#539]
ip add show :
    inet 192.168.21.225/24 brd 192.168.21.255 scope global eth0
    inet 192.168.21.25/24 brd 192.168.21.255 scope global secondary eth0

Gathering the hardware ip address gets the secondary ip address instead of the primary one.

rex -H host -e "dump_system_information"
..
$lo_is_bridge = '0'
$eth0_ip = '192.168.21.225'
...

In this case, rex should care of both info. For example:
..
$lo_is_bridge = '0'
$eth0_ip = '192.168.21.25'
$eth0_secondary_ip = '192.168.21.225'
...

**Comment by krimdomu** [comment]
Hi samuelet,

thanks for this report. I'll take a look at it.

**Comment by krimdomu** [comment]
Hi,

i think the issue is fixed with the above commit. If you want to try it, you can just download the file from (1) and replace the one from your installation.

This fix will be included in the next release.

(1) https://raw.githubusercontent.com/RexOps/Rex/9cd62be10bf052fef7becddecec6683135e696fb/lib/Rex/Hardware/Network/Linux.pm

**Comment by krimdomu** [comment]
This patch will add a new entry for every secondary ip in the form of:

eth0_1_ip
eth0_2_ip
...

**Comment by samuelet** [comment]
tested and it works perfectly, thanks.
