### ISSUE TITLE
Can we pass the task args to before_task_start()?

### ISSUE THREAD

**Issue by kablamo** [RexOps/Rex#628]
Can we pass the task args to before_task_start()?  I'd like to modify the task args in before_task_start().  

Am happy to submit a pr for that if you agree

**Comment by kablamo** [comment]
Might be useful to pass the server list ref as well?

**Comment by ferki** [comment]
@kablamo: sorry for the untimely response. We can of course discuss this, especially since `before`/`after`/`around` has this option, and it sounds like a good idea to provide the same options among those commands.

Can you also provide me an example use case, please? I'd like to understand the situation where it might be needed in practice (I mean I never had to actually use these guys for some reason, so on my own I don't really see the problem we're trying to solve here).

**Comment by kablamo** [comment]
No worries @ferki.  I closed it because I'm thinking of doing it differently and already have something in another pr.  My plan was to add task options to the Rex::Task object.  If we do that, then this is no longer necessary.
