### ISSUE TITLE
exit(1) from a task doesn't exit from rex

### ISSUE THREAD

**Issue by kablamo** [RexOps/Rex#630]
The process exists I guess, but not rex.  I'm using the 'exec_autodie' feature.  Maybe I could add an 'exec autoexit' feature.

**Comment by ferki** [comment]
hi kablamo, AFAIK this is due to the fact that rex forks before executing tasks, so an exit(1) will only finishe that child process (see similar related issues #400 and #295). There are some interesting non-trivial questions in this problem domian, like:
- what should happen if there are multiple tasks running in parallel and/or on multiple servers and only one or some of them has to `exit(1)`
- should the other tasks continue? should they also stop?
- if they should stop, how do they communicate this fact between each other?
- what should be the overall exit code on partial failures?
- how does this affect transactional tasks and their rollbacks?

I think most of that behavior should be configurable (at least sooner or later, but it should be kept in mind).

We believe that `Parallel::ForkManager` can help solving most (if not all) of those questions and there is already an experimental support for it, so you may want to look into that.

I also believe that any progress in this direction would be warmly welcome, while also needs to be discussed and tested carefully.

**Comment by krimdomu** [comment]
There is a small module on modules.rexify.org which shows how to "fail". This module allows to specify on how many servers a task can fail before rex is going to stop everything.

Maybe this helps you. 

Doc: http://modules.rexify.org/module/Rex::Ext::Fail
Code: https://github.com/RexOps/rex-recipes/tree/1.1/Rex/Ext/Fail

**Comment by krimdomu** [comment]
This module needs Parallel::ForkManager to be installed
