### ISSUE TITLE
rex -T namespace

### ISSUE THREAD

**Issue by kablamo** [RexOps/Rex#631]
Lets say `rex -T` outputs the following
```
Tasks
 a:apple
 deploy:a
 deploy:b
 deploy:c
 git:pull
 grep:logs
 r:river
 z:zebra
```
We have a lot of tasks.  So it would be nice if `rex -T deploy` acted to filter everything but the deploy tasks so the output looks like this:
```
 deploy:a
 deploy:b
 deploy:c
```

**Comment by kablamo** [comment]
Sorry I keep making tickets and not submitting pull requests.  Am hoping to circle around and solve at least some of these.

**Comment by ferki** [comment]
@kablamo: no problem at all, we really appreciate feedback and especially opening issues ;) This is really a good idea and I thought it's already there as it works when a taskname is passed. But looks like it does not work in the general case since it breaks when only submodule names are passed.

Alternatively/additionally a `-Tf` switch can be introduced to perform a search for the passed argument in the list of all tasknames (e.g. to be able to find substrings in the middle of them).

**Comment by krimdomu** [comment]
Yes, this is a really good idea. :+1:

**Comment by kablamo** [comment]
feature added
