### ISSUE TITLE
Create homebrew formula

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#637]
During our colleagues experiments to streamline/simplify Rex installation on Mac OS X, we concluded that it would be reasonably simple to write a homebrew formula for rex. As I believe we, Rex developers in general, are not (active) OS X users, any help would be appreciated in this direction :)

**Comment by yko** [comment]
This could start with a [naive implementation](https://gist.github.com/yko/3d45bb9fd311d326423038f322f8b497) that just works.
Two problem I see with the naive approach is that `cpanm` would install in Rex's libexec path latest releases of all (only) missing dependencies.
Hence, potential breakages because of newer releases and potential breakages because of dependencies removed from the system.

I feel that [extract_url.pl](https://github.com/Homebrew/homebrew-core/blob/master/Formula/extract_url.rb) approach would be better, but it would require describing desired versions of  non-core dependencies in a `resource` manner.

I will leave this note here in case I'm not making it myself

**Comment by ferki** [comment]
@yko: thanks for your initial work and input to inspire us!

Thanks to @andrewslotin via Homebrew/homebrew-core#12561, rex-1.5.0 now can be installed with homebrew :tada:
