### ISSUE TITLE
Misleading error message when the host identity key changes

### ISSUE THREAD

**Issue by andrewslotin** [RexOps/Rex#671]
When Rex fails to connect to host via SSH because of host identity key has been changed, e.g. when using Vagrant to test provisioning locally, it prints out the following message
```
Error running task/batch: Wrong username/password or wrong key on 127.0.0.1. at /Library/Perl/5.18/Rex/TaskList/Base.pm line 295"
```
Whereas I would expect something like 
```
Remote host identification has changed. If this is expected, please remove stale record from ~/.ssh/known_hosts or put Rex::Config->set_openssh_opt(StrictHostKeyChecking => 'no') into your Rexfile.
```
Here is the original message printed by `ssh`:
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
<...>
RSA host key for [127.0.0.1]:2222 has changed and you have requested strict checking.
Host key verification failed.
```

**Comment by ferki** [comment]
@andrewslotin: thanks for your report, I agree that the mentioned error message can be improved :)

We already talked about this, and is unrelated to the above fact, but I felt it is worth mentioning here for others, that Rex::Box can be used for basically the same stuff as Vagrant (and it already handles this situation internally :).

**Comment by ferki** [comment]
@andrewslotin: until the underlying `Net::OpenSSH` module gains possibility to recognize this situation and/or to expose the raw output of openssh master processes (see related upstream issue above), I can only give you some ideas what could be done (one of them may very well needed in your mentioned use case anyway because of the constantly/rapidly changing host keys)

- disable strict host key checking by either using:
 - `disable_strict_host_key_checking` Rex feature flag:
`use Rex -feature => ['disable_strict_host_key_checking'];`

 - passing `StrictHostKeyChecking => 'no'` as OpenSSH option:
`Rex::Config->set_openssh_opt( StrictHostKeyChecking => 'no' );`

 - putting `StrictHostKeyChecking no` into your `/etc/ssh/ssh_config` or into `~/.ssh/config` (please be advised that this will disable host key checking in general, only do this if you understand its security implications - it's only listed here for sake of completeness)

- using `Net::SSH2` instead of `Net::OpenSSH` as that module uses `libssh2` and not the openssh binary

I would recommend using the feature flag.

**Comment by ferki** [comment]
@andrewslotin: unfortunately Net::OpenSSH still can't reliably return this exact type of failure, so I decided to just mention this case as a possible cause of authentication problem.

The error message of Rex contains the message returned by the the underlying connection layer, so once it's fixed there, Rex will automagically get the fix too.
