### ISSUE TITLE
bulk install is broken

### ISSUE THREAD

**Issue by ferki** [RexOps/Rex#838]
b03eecd0b18516c34b141d406aa1239149f66151 forces `pkg` to be called one-by-one on all passed packages in an arrayref, which makes the package manager to be called as many times as many elements are in the list.

This is basically avoiding `bulk_install` to be called, and adds considerable amount of overhead, slowing down the whole process.

It would be nice if we could do the per-package reporting in a different form, and/or at least tieing this behaviour to a feature flag.

**Comment by krimdomu** [comment]
this was by intent, because the bulk install breaks the `on_change` hook which is more important than speed, imho (for example if a service like httpd was updated, you need to restart it)

maybe we can refactor the package classes to return what packges they installed/updated and depending on this information run the `on_change` hook and do the reporting.

**Comment by ferki** [comment]
Thanks for the explanation!

**Comment by ferki** [comment]
@krimdomu suggested via IRC that [Rex::Pkg::Base::diff_package_list](https://github.com/RexOps/Rex/blob/development/lib/Rex/Pkg/Base.pm#L187-L226) can be used to help generating the report after a bulk install is done.
