### ISSUE TITLE
openwrt - many failures in test

### ISSUE THREAD

**Issue by krimdomu** [RexOps/Rex#898]
https://build.rexify.org/job/Test%20-%20OpenWrt%2014.07%20%28i386%29/26/console

**Comment by ferki** [comment]
Some tests were fixed in RexOps/rex-build repo. Now it passes for me locally both with Net::OpenSSH and Net::SSH2. However, in Jenkins, it is only passing with Net::OpenSSH, so I guess there are some test-related issue is going on.

All in all, I think we can close this, and go ahead with releasing 1.4.0(RC), and track the testing issue elsewhere.

If no objections, I'm going to close it and go ahead with the release soon (after merging #907 too).

**Comment by krimdomu** [comment]
+1
