### ISSUE TITLE
Dist::Zilla creates some wrong dependencies

### ISSUE THREAD

**Issue by krimdomu** [RexOps/Rex#971]
For example it puts Parallel::ForkManager, Xml::LibXML and String::Escape into the "test" section.

**Comment by ferki** [comment]
I guess that's because those are optional dependencies, but we do have tests for them, so it has no better way than put it into the test section.

Maybe we can mark optional dependencies as recommended deps, or try to use something like [Dist::Zilla::Plugin::OptionalFeature](https://metacpan.org/pod/Dist::Zilla::Plugin::OptionalFeature).

**Comment by krimdomu** [comment]
I think the dependencies are now right. So i'm closing this issue.
