### ISSUE TITLE
CMDB is only loading variables in local Scope

### ISSUE THREAD

**Issue by ben-stein** [RexOps/Rex#988]
if i want to load Variables from the cmdb in a rex task then i have to define them in the task(local scope).
I cannot use them if i define them on global Scope.

an Example i have specified a default.yml and a hostname.domain.yml file in the Rexfile.
now i want to use the cmdb in let's say an uptime.task:

```

my $foo = get cmdb foo;

task "uptime", group => "servers", sub {

say $foo;
```

This will not work since it is not loading the cmdb on runtime, because it is somehow not "in use"
In the log it will display the current server instead of the connection server in the cmdb section.

On the other Hand this example will work:

```
task "uptime", group => "servers", sub {

my $foo = get cmdb foo;
say $foo;
```

Is this expected behavior?

**Comment by krimdomu** [comment]
Hi @ben-stein 

yes this is the expected behavior. But it might not be transparent to users which are not that familiar with programming.

The problem here is, that `get cmdb "something"` returns a static variable (a hash or a scalar) which will not change if it is called in another scope.

A possible solution would be that `get cmdb` returns an object which then queries the cmdb data when someone want to retrieve the real data. But i don't know if the time you need to write that (and to be compatible to the current behavior of normal variables) justify the (maybe) more transparent usage.

**Comment by ben-stein** [comment]
that sounds about right :)
